# Site
name: "Kriszti치n Papp"
title: "Kriszti치n Papp"
description: "Sharing lessons, insights, and stories from my journey as a developer."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "" 
google_analytics: ''
disqus: 'kpapp-dev'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kpapp:
    name: kpapp
    display_name: Kriszti치n Papp
    gravatar: d800d91eb063cfa17311352c718f19d0
    email: me@kpapp.dev
    web: https://kpapp.dev
    twitter: https://twitter.com/tacsiazuma
    description: "Kriszti치n is a principal engineer at Diligent with over a decade of hands-on experience in creating and maintaining software. He is the founder of the Letscode.hu community, creating a supportive environment where individuals can thrive, share their knowledge, and collectively contribute to the advancement of technology."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
